<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Figure 1 | _main.knit</title>
  <meta name="description" content="This bookdown project contains raw data, data analyses, and code to generate analyses for the paper “A history of injury enhances affective and sensory responses to predator threat via sensitization of corticosterone release through TRPA1 receptor signaling”." />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="Figure 1 | _main.knit" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This bookdown project contains raw data, data analyses, and code to generate analyses for the paper “A history of injury enhances affective and sensory responses to predator threat via sensitization of corticosterone release through TRPA1 receptor signaling”." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Figure 1 | _main.knit" />
  
  <meta name="twitter:description" content="This bookdown project contains raw data, data analyses, and code to generate analyses for the paper “A history of injury enhances affective and sensory responses to predator threat via sensitization of corticosterone release through TRPA1 receptor signaling”." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="about.html"/>
<link rel="next" href="figure-2.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="about.html"><a href="about.html"><i class="fa fa-check"></i>About</a></li>
<li class="chapter" data-level="" data-path="figure-1.html"><a href="figure-1.html"><i class="fa fa-check"></i>Figure 1</a>
<ul>
<li class="chapter" data-level="" data-path="figure-1.html"><a href="figure-1.html#time-spent-freezing-during-tmt"><i class="fa fa-check"></i>Time Spent Freezing During TMT</a></li>
<li class="chapter" data-level="" data-path="figure-1.html"><a href="figure-1.html#frequency-of-freezing-during-tmt"><i class="fa fa-check"></i>Frequency of Freezing During TMT</a></li>
<li class="chapter" data-level="" data-path="figure-1.html"><a href="figure-1.html#linear-relationship-between-time-with-tmt-and-length-of-freeze"><i class="fa fa-check"></i>Linear relationship between Time With TMT and Length of Freeze</a></li>
<li class="chapter" data-level="" data-path="figure-1.html"><a href="figure-1.html#percent-freezing-split-by-minute-with-tmt"><i class="fa fa-check"></i>Percent Freezing Split by Minute With TMT</a></li>
<li class="chapter" data-level="" data-path="figure-1.html"><a href="figure-1.html#analysis-of-distribution-of-length-of-freezing-bouts"><i class="fa fa-check"></i>Analysis of Distribution of Length of Freezing Bouts</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="figure-2.html"><a href="figure-2.html"><i class="fa fa-check"></i>Figure 2</a>
<ul>
<li class="chapter" data-level="" data-path="figure-2.html"><a href="figure-2.html#von-frey-paw-sensitivity-after-tmt"><i class="fa fa-check"></i>Von Frey Paw Sensitivity After TMT</a></li>
<li class="chapter" data-level="" data-path="figure-2.html"><a href="figure-2.html#hot-plate-test"><i class="fa fa-check"></i>Hot Plate Test</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="figure-3.html"><a href="figure-3.html"><i class="fa fa-check"></i>Figure 3</a>
<ul>
<li class="chapter" data-level="" data-path="figure-3.html"><a href="figure-3.html#overall-effects-of-stress-and-timepoint"><i class="fa fa-check"></i>Overall Effects of Stress and Timepoint</a></li>
<li class="chapter" data-level="" data-path="figure-3.html"><a href="figure-3.html#follow-ups-effect-of-cfa-at-each-timepoint"><i class="fa fa-check"></i>Follow Ups: Effect of CFA at Each Timepoint</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="figure-4.html"><a href="figure-4.html"><i class="fa fa-check"></i>Figure 4</a>
<ul>
<li class="chapter" data-level="" data-path="figure-4.html"><a href="figure-4.html#time-spent-freezing-behavior-during-tmt"><i class="fa fa-check"></i>Time Spent Freezing Behavior During TMT</a></li>
<li class="chapter" data-level="" data-path="figure-4.html"><a href="figure-4.html#raw-vf-scores"><i class="fa fa-check"></i>Raw VF scores</a></li>
<li class="chapter" data-level="" data-path="figure-4.html"><a href="figure-4.html#vf-thresholds-relative-to-baseline-measurements"><i class="fa fa-check"></i>VF Thresholds Relative to Baseline Measurements</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="figure-5.html"><a href="figure-5.html"><i class="fa fa-check"></i>Figure 5</a>
<ul>
<li class="chapter" data-level="" data-path="figure-5.html"><a href="figure-5.html#effect-of-cfa-for-saline-treated-mice"><i class="fa fa-check"></i>Effect of CFA for Saline-Treated Mice</a></li>
<li class="chapter" data-level="" data-path="figure-5.html"><a href="figure-5.html#no-effect-of-cfa-for-metyrapone-treated-mice"><i class="fa fa-check"></i>No Effect of CFA for Metyrapone-Treated Mice</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="figure-6.html"><a href="figure-6.html"><i class="fa fa-check"></i>Figure 6</a>
<ul>
<li class="chapter" data-level="" data-path="figure-6.html"><a href="figure-6.html#blood-cort-levels"><i class="fa fa-check"></i>Blood CORT Levels</a></li>
<li class="chapter" data-level="" data-path="figure-6.html"><a href="figure-6.html#percent-freezing-during-tmt"><i class="fa fa-check"></i>Percent Freezing During TMT</a></li>
<li class="chapter" data-level="" data-path="figure-6.html"><a href="figure-6.html#freezing-frequency-during-tmt"><i class="fa fa-check"></i>Freezing Frequency During TMT</a></li>
<li class="chapter" data-level="" data-path="figure-6.html"><a href="figure-6.html#freezing-during-each-minute-of-tmt"><i class="fa fa-check"></i>Freezing During Each Minute of TMT</a></li>
<li class="chapter" data-level="" data-path="figure-6.html"><a href="figure-6.html#linear-relationship-between-time-and-length-of-freeze"><i class="fa fa-check"></i>Linear Relationship Between Time and Length of Freeze</a></li>
<li class="chapter" data-level="" data-path="figure-6.html"><a href="figure-6.html#analysis-of-distribution-of-length-of-freezing-episodes"><i class="fa fa-check"></i>Analysis of Distribution of Length of Freezing Episodes</a></li>
<li class="chapter" data-level="" data-path="figure-6.html"><a href="figure-6.html#von-frey-thresholds-after-tmt"><i class="fa fa-check"></i>Von Frey Thresholds After TMT</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="figure-7.html"><a href="figure-7.html"><i class="fa fa-check"></i>Figure 7</a></li>
<li class="chapter" data-level="" data-path="supplemental-figure-1.html"><a href="supplemental-figure-1.html"><i class="fa fa-check"></i>Supplemental Figure 1</a>
<ul>
<li class="chapter" data-level="" data-path="supplemental-figure-1.html"><a href="supplemental-figure-1.html#raw-vf-values"><i class="fa fa-check"></i>Raw VF Values</a></li>
<li class="chapter" data-level="" data-path="supplemental-figure-1.html"><a href="supplemental-figure-1.html#within-subjects-changes-in-vf-threasholds"><i class="fa fa-check"></i>Within-Subjects’ Changes in VF Threasholds</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="supplemental-figure-2.html"><a href="supplemental-figure-2.html"><i class="fa fa-check"></i>Supplemental Figure 2</a></li>
<li class="chapter" data-level="" data-path="supplemental-figure-3.html"><a href="supplemental-figure-3.html"><i class="fa fa-check"></i>Supplemental Figure 3</a>
<ul>
<li class="chapter" data-level="" data-path="supplemental-figure-3.html"><a href="supplemental-figure-3.html#cort-levels"><i class="fa fa-check"></i>CORT Levels</a></li>
<li class="chapter" data-level="" data-path="supplemental-figure-3.html"><a href="supplemental-figure-3.html#time-spent-freezing-during-tmt-1"><i class="fa fa-check"></i>Time Spent Freezing During TMT</a></li>
<li class="chapter" data-level="" data-path="supplemental-figure-3.html"><a href="supplemental-figure-3.html#freezing-frequency-during-tmt-1"><i class="fa fa-check"></i>Freezing Frequency During TMT</a></li>
<li class="chapter" data-level="" data-path="supplemental-figure-3.html"><a href="supplemental-figure-3.html#freezing-each-minute-with-tmt"><i class="fa fa-check"></i>Freezing Each Minute With TMT</a></li>
<li class="chapter" data-level="" data-path="supplemental-figure-3.html"><a href="supplemental-figure-3.html#linear-relationship-between-time-and-length-of-freeze-1"><i class="fa fa-check"></i>Linear Relationship Between Time and Length of Freeze</a></li>
<li class="chapter" data-level="" data-path="supplemental-figure-3.html"><a href="supplemental-figure-3.html#von-frey-paw-sensitivity"><i class="fa fa-check"></i>Von Frey Paw Sensitivity</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="supplemental-figure-4.html"><a href="supplemental-figure-4.html"><i class="fa fa-check"></i>Supplemental Figure 4</a></li>
<li class="chapter" data-level="" data-path="supplemental-figure-5.html"><a href="supplemental-figure-5.html"><i class="fa fa-check"></i>Supplemental Figure 5</a>
<ul>
<li class="chapter" data-level="" data-path="supplemental-figure-5.html"><a href="supplemental-figure-5.html#cort-levels-1"><i class="fa fa-check"></i>CORT Levels</a></li>
<li class="chapter" data-level="" data-path="supplemental-figure-5.html"><a href="supplemental-figure-5.html#time-spent-freezing-during-tmt-2"><i class="fa fa-check"></i>Time Spent Freezing During TMT</a></li>
<li class="chapter" data-level="" data-path="supplemental-figure-5.html"><a href="supplemental-figure-5.html#frequency-of-freezing-during-tmt-1"><i class="fa fa-check"></i>Frequency of Freezing During TMT</a></li>
<li class="chapter" data-level="" data-path="supplemental-figure-5.html"><a href="supplemental-figure-5.html#length-of-freezing-bouts"><i class="fa fa-check"></i>Length of Freezing Bouts</a></li>
<li class="chapter" data-level="" data-path="supplemental-figure-5.html"><a href="supplemental-figure-5.html#von-frey-sensitivity"><i class="fa fa-check"></i>Von Frey Sensitivity</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="supplemental-figure-6.html"><a href="supplemental-figure-6.html"><i class="fa fa-check"></i>Supplemental Figure 6</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="figure-1" class="section level1 unnumbered hasAnchor">
<h1>Figure 1<a href="figure-1.html#figure-1" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><img src="Figs/1_TMT_CFA_Frz.png" width="1350" /></p>
<p><strong>Figure 1. <em>A history of CFA injury enhances TMT-induced freezing behavior.</em></strong> (A) Timeline for behavioral testing: 10 μL of 50% CFA injected into the footpad of the left hind paw was used as a model of injury, which produces a robust pain phenotype that reliably resolves within 7 days post-injection. Ten days after CFA, mice were tested for basal freezing levels and freezing during presentation of the single-molecule odor TMT. (B) Raster plots showing freezing behavior across the five-minute exposure to TMT. (C) CFA-primed mice spent more time freezing than pain-naive controls during TMT exposure. (D) Freezing behavior during each minute of TMT exposure. (E) Number of freezing episodes during TMT. (F) Linear relationship between time spent with TMT and length of freezing episodes. (G) Density plots showing the distribution of individual bouts of freezing compared between naive and CFA-primed mice. (H) Cumulative proportion of bouts of freezing during the TMT session. Data displayed as mean +/- SEM. ** indicates p &lt; 0.01, *** indicates p &lt; 0.001.</p>
<div id="time-spent-freezing-during-tmt" class="section level2 unnumbered hasAnchor">
<h2>Time Spent Freezing During TMT<a href="figure-1.html#time-spent-freezing-during-tmt" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="figure-1.html#cb1-1" tabindex="-1"></a>b <span class="ot">&lt;-</span> Exp_1_CFA.N  <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="figure-1.html#cb1-2" tabindex="-1"></a>  <span class="fu">filter</span>(Behavior <span class="sc">==</span> <span class="st">&quot;freeze&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-3"><a href="figure-1.html#cb1-3" tabindex="-1"></a>  <span class="fu">group_by</span>(ID,CFA) <span class="sc">%&gt;%</span></span>
<span id="cb1-4"><a href="figure-1.html#cb1-4" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb1-5"><a href="figure-1.html#cb1-5" tabindex="-1"></a>    <span class="at">sum=</span><span class="fu">sum</span>(Duration),</span>
<span id="cb1-6"><a href="figure-1.html#cb1-6" tabindex="-1"></a>    <span class="at">Number=</span><span class="fu">n</span>(),</span>
<span id="cb1-7"><a href="figure-1.html#cb1-7" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb1-8"><a href="figure-1.html#cb1-8" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Perc =</span> (sum <span class="sc">/</span> <span class="dv">300</span>)<span class="sc">*</span><span class="dv">100</span>)</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;ID&#39;. You can override using the `.groups`
## argument.</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="figure-1.html#cb3-1" tabindex="-1"></a><span class="fu">t.test</span>(Perc<span class="sc">~</span>CFA,<span class="at">data=</span>b,<span class="at">var.equal=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  Perc by CFA
## t = -2.8169, df = 28, p-value = 0.00879
## alternative hypothesis: true difference in means between group Naive and group CFA is not equal to 0
## 95 percent confidence interval:
##  -21.59481  -3.41081
## sample estimates:
## mean in group Naive   mean in group CFA 
##            22.00138            34.50420</code></pre>
<p>Across the 5-minute exposure to TMT, mice that had previously experienced CFA spent more time freezing than did pain naive controls (<em>t</em>(28) = 2.82, <em>p</em> = 0.009).</p>
</div>
<div id="frequency-of-freezing-during-tmt" class="section level2 unnumbered hasAnchor">
<h2>Frequency of Freezing During TMT<a href="figure-1.html#frequency-of-freezing-during-tmt" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="figure-1.html#cb5-1" tabindex="-1"></a><span class="fu">t.test</span>(Number<span class="sc">~</span>CFA,<span class="at">data=</span>b,<span class="at">var.equal=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  Number by CFA
## t = -2.0875, df = 28, p-value = 0.04606
## alternative hypothesis: true difference in means between group Naive and group CFA is not equal to 0
## 95 percent confidence interval:
##  -15.0432681  -0.1422523
## sample estimates:
## mean in group Naive   mean in group CFA 
##            38.23077            45.82353</code></pre>
<p>Overall, CFA-primed mice froze more frequently than naive mice (<em>t</em>(28) = 2.087, <em>p</em> = 0.046).</p>
</div>
<div id="linear-relationship-between-time-with-tmt-and-length-of-freeze" class="section level2 unnumbered hasAnchor">
<h2>Linear relationship between Time With TMT and Length of Freeze<a href="figure-1.html#linear-relationship-between-time-with-tmt-and-length-of-freeze" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="figure-1.html#cb7-1" tabindex="-1"></a><span class="co"># model the linear relationship between time and length of freeze</span></span>
<span id="cb7-2"><a href="figure-1.html#cb7-2" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">lm</span>(Duration<span class="sc">~</span>Start_clean <span class="sc">*</span> CFA, <span class="at">data=</span>Exp_1_CFA.N)</span>
<span id="cb7-3"><a href="figure-1.html#cb7-3" tabindex="-1"></a><span class="fu">summary</span>(b)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Duration ~ Start_clean * CFA, data = Exp_1_CFA.N)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.7754 -1.0071 -0.5278  0.1559 22.2313 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         0.868308   0.158525   5.477 4.87e-08 ***
## Start_clean         0.004963   0.000912   5.442 5.92e-08 ***
## CFACFA             -0.065515   0.200135  -0.327   0.7434    
## Start_clean:CFACFA  0.002793   0.001165   2.398   0.0166 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.068 on 1978 degrees of freedom
##   (60 observations deleted due to missingness)
## Multiple R-squared:  0.07253,    Adjusted R-squared:  0.07113 
## F-statistic: 51.56 on 3 and 1978 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The significant interaction between time and CFA indicates that the increase in length of freezing episode across the five-minute session differs for Naive and CFA-primed mice (p = 0.01).</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="figure-1.html#cb9-1" tabindex="-1"></a>Naives <span class="ot">&lt;-</span> Exp_1_CFA.N[Exp_1_CFA.N<span class="sc">$</span>CFA <span class="sc">==</span> <span class="st">&quot;Naive&quot;</span>, ]</span>
<span id="cb9-2"><a href="figure-1.html#cb9-2" tabindex="-1"></a>c <span class="ot">&lt;-</span> <span class="fu">lm</span>(Duration<span class="sc">~</span>Start_clean, <span class="at">data =</span> Naives)</span>
<span id="cb9-3"><a href="figure-1.html#cb9-3" tabindex="-1"></a><span class="fu">summary</span>(c)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Duration ~ Start_clean, data = Naives)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.8727 -0.8969 -0.4920  0.0922 22.2313 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 0.8683076  0.1576737   5.507 4.92e-08 ***
## Start_clean 0.0049630  0.0009071   5.471 5.97e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.057 on 803 degrees of freedom
##   (26 observations deleted due to missingness)
## Multiple R-squared:  0.03594,    Adjusted R-squared:  0.03474 
## F-statistic: 29.94 on 1 and 803 DF,  p-value: 5.967e-08</code></pre>
<p>For naive mice, a 1-second increase in time in the apparatus with TMT was associated with a 49.6 ms increase in predicted length of freeze.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="figure-1.html#cb11-1" tabindex="-1"></a>CFAs <span class="ot">&lt;-</span> Exp_1_CFA.N[Exp_1_CFA.N<span class="sc">$</span>CFA <span class="sc">==</span> <span class="st">&quot;CFA&quot;</span>, ]</span>
<span id="cb11-2"><a href="figure-1.html#cb11-2" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">lm</span>(Duration<span class="sc">~</span>Start_clean, <span class="at">data =</span> CFAs)</span>
<span id="cb11-3"><a href="figure-1.html#cb11-3" tabindex="-1"></a><span class="fu">summary</span>(d)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Duration ~ Start_clean, data = CFAs)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.7754 -1.1509 -0.5655  0.2294 15.8554 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 0.8027926  0.1226094   6.548 8.72e-11 ***
## Start_clean 0.0077559  0.0007271  10.667  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.076 on 1175 degrees of freedom
##   (34 observations deleted due to missingness)
## Multiple R-squared:  0.08829,    Adjusted R-squared:  0.08751 
## F-statistic: 113.8 on 1 and 1175 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>For CFA-primed mice, a 1-second increase in time spent with TMT was associated with a 77.56 ms increase in predicted length of freeze.</p>
<ul>
<li>The predicted second-by-second increase in freezing time was 56% greater than the predicted change for naive mice.</li>
</ul>
</div>
<div id="percent-freezing-split-by-minute-with-tmt" class="section level2 unnumbered hasAnchor">
<h2>Percent Freezing Split by Minute With TMT<a href="figure-1.html#percent-freezing-split-by-minute-with-tmt" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Data binned by minute:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="figure-1.html#cb13-1" tabindex="-1"></a>a <span class="ot">&lt;-</span> Exp_1_CFA.N <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="figure-1.html#cb13-2" tabindex="-1"></a>  <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="figure-1.html#cb13-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Bins =</span> <span class="fu">cut</span>(</span>
<span id="cb13-4"><a href="figure-1.html#cb13-4" tabindex="-1"></a>    Start_clean,</span>
<span id="cb13-5"><a href="figure-1.html#cb13-5" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="dv">5</span>,</span>
<span id="cb13-6"><a href="figure-1.html#cb13-6" tabindex="-1"></a>    <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;1&quot;</span>,<span class="st">&quot;2&quot;</span>,<span class="st">&quot;3&quot;</span>,<span class="st">&quot;4&quot;</span>,<span class="st">&quot;5&quot;</span>)</span>
<span id="cb13-7"><a href="figure-1.html#cb13-7" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span></span>
<span id="cb13-8"><a href="figure-1.html#cb13-8" tabindex="-1"></a>  <span class="fu">group_by</span>(ID, Behavior, CFA, PGE2, Bins) <span class="sc">%&gt;%</span></span>
<span id="cb13-9"><a href="figure-1.html#cb13-9" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb13-10"><a href="figure-1.html#cb13-10" tabindex="-1"></a>    <span class="at">sum =</span> <span class="fu">sum</span> (Duration)</span>
<span id="cb13-11"><a href="figure-1.html#cb13-11" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb13-12"><a href="figure-1.html#cb13-12" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Perc =</span> (sum <span class="sc">/</span> <span class="dv">60</span>)<span class="sc">*</span><span class="dv">100</span> ) <span class="sc">%&gt;%</span></span>
<span id="cb13-13"><a href="figure-1.html#cb13-13" tabindex="-1"></a>  <span class="fu">filter</span>(Behavior <span class="sc">==</span> <span class="st">&quot;freeze&quot;</span>)</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;ID&#39;, &#39;Behavior&#39;, &#39;CFA&#39;, &#39;PGE2&#39;. You can
## override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="figure-1.html#cb15-1" tabindex="-1"></a>anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(Perc<span class="sc">~</span>Bins<span class="sc">*</span>CFA,<span class="at">data=</span>a)</span>
<span id="cb15-2"><a href="figure-1.html#cb15-2" tabindex="-1"></a><span class="fu">summary</span>(anova)</span></code></pre></div>
<pre><code>##              Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Bins          4  25857    6464  22.589 2.82e-14 ***
## CFA           1   5940    5940  20.758 1.16e-05 ***
## Bins:CFA      4    483     121   0.422    0.793    
## Residuals   134  38346     286                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Freezing increased across the five minutes of exposure to TMT (F(4,134) = 22.59, p &lt; 0.001), and CFA-primed mice froze more than naive controls (F(1,134) = 20.76, p &lt; 0.001).</p>
</div>
<div id="analysis-of-distribution-of-length-of-freezing-bouts" class="section level2 unnumbered hasAnchor">
<h2>Analysis of Distribution of Length of Freezing Bouts<a href="figure-1.html#analysis-of-distribution-of-length-of-freezing-bouts" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="figure-1.html#cb17-1" tabindex="-1"></a><span class="fu">library</span>(kSamples)</span>
<span id="cb17-2"><a href="figure-1.html#cb17-2" tabindex="-1"></a></span>
<span id="cb17-3"><a href="figure-1.html#cb17-3" tabindex="-1"></a>a <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb17-4"><a href="figure-1.html#cb17-4" tabindex="-1"></a>  <span class="fu">filter</span>(CFA <span class="sc">!=</span> <span class="st">&quot;CFA_1D&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-5"><a href="figure-1.html#cb17-5" tabindex="-1"></a>  <span class="fu">filter</span>(PGE2 <span class="sc">!=</span> <span class="st">&quot;PGE2&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-6"><a href="figure-1.html#cb17-6" tabindex="-1"></a>  <span class="fu">filter</span>(Behavior <span class="sc">==</span> <span class="st">&quot;freeze&quot;</span>)</span>
<span id="cb17-7"><a href="figure-1.html#cb17-7" tabindex="-1"></a></span>
<span id="cb17-8"><a href="figure-1.html#cb17-8" tabindex="-1"></a>cfa_durations <span class="ot">&lt;-</span> a<span class="sc">$</span>Duration[a<span class="sc">$</span>CFA <span class="sc">==</span> <span class="st">&quot;CFA&quot;</span>]</span>
<span id="cb17-9"><a href="figure-1.html#cb17-9" tabindex="-1"></a>naive_durations <span class="ot">&lt;-</span> a<span class="sc">$</span>Duration[a<span class="sc">$</span>CFA <span class="sc">==</span> <span class="st">&quot;Naive&quot;</span>]</span>
<span id="cb17-10"><a href="figure-1.html#cb17-10" tabindex="-1"></a></span>
<span id="cb17-11"><a href="figure-1.html#cb17-11" tabindex="-1"></a><span class="fu">ad.test</span>(cfa_durations, naive_durations)</span></code></pre></div>
<pre><code>## 
## 
##  Anderson-Darling k-sample test.
## 
## Number of samples:  2
## Sample sizes:  779, 497
## Number of ties: 979
## 
## Mean of  Anderson-Darling  Criterion: 1
## Standard deviation of  Anderson-Darling  Criterion: 0.76026
## 
## T.AD = ( Anderson-Darling  Criterion - mean)/sigma
## 
## Null Hypothesis: All samples come from a common population.
## 
##                AD   T.AD  asympt. P-value
## version 1: 10.595 12.621       4.7634e-06
## version 2: 10.600 12.632       4.7527e-06</code></pre>
<p>To compare the distribution of individual freezing episodes between CFA and Naive mice, an Anderson-Darling k-sample test was conducted. The test revealed a significant difference between the two distributions, (AD = 10.50, p &lt; .001), indicating that mice with a history of CFA exhibited a shifted distribution of freezing duration compared to pain-naive mice.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="about.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="figure-2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["_main.pdf", "_main.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "download": ["pdf", "epub"]
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
